branches:
  only:
    - /^2.*$/
language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - mark.carver@me.com
    on_success: never # default: change
    on_failure: always # default: always
  irc:
    channels:
      - "chat.freenode.net#dreditor"
    use_notice: true
    skip_join: true
